name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.2
  firebase_core: ^2.12.0
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  data_management:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true